
fullnameOverride: "saver"

updateStrategy: "Recreate"

replicaCount: 1

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: saver-tmp-dir
    emptyDir: {}
  - name: saver-data
    persistentVolumeClaim:
      claimName: saver-data

containers:
  - name: saver
    volumeMounts:
      - name: saver-tmp-dir
        mountPath: /tmp
        readOnly: false
      - name: saver-data
        mountPath: /cyber-dojo
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
    #livenessProbe:
    #  path: /alive?
    #  port: 4537
    #readinessProbe:
    #  path: /ready?
    #  port: 4537

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
