# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# app name
fullnameOverride: "saver"

# deployment spec
replicaCount: 1
updateStrategy: "Recreate"

volumes:
  - name: saver-tmp-dir
    emptyDir: {}
  - name: saver-data
    persistentVolumeClaim:
      claimName: saver-data

initContainers:
- name: volume-mount-hack
  image: busybox
  tag: latest
  command: [ "/bin/sh"]
  args:
    - "-c"
    - "chown -R 19663:65533 /cyber-dojo"
  volumeMounts:
  - name: saver-data
    mountPath: /cyber-dojo
# containers
# provide default values that you HAVE to overwrite in your values.yaml file
containers:
  - name: saver
    image: cyberdojo/saver
    tag: "a6d71a0"
    securityContext:
      runAsUser: 19663
      fsGroup: 65533
    volumeMounts:
      - name: saver-tmp-dir
        mountPath: /tmp
        readOnly: false
      - name: saver-data
        mountPath: /cyber-dojo


    resources:
      limits:
       memory: 256Mi
      requests:
       memory: 256Mi
    # livenessProbe:
    #   path: /health
    #   port: 80
    # readinessProbe:
    #   path: /health
    #   port: 80

envFromSecret: {}


nodeSelector: {}

affinity: {}

tolerations: []

# service
service:
  port: 4537

pvc:
  name: saver-data
  storage: 500Gi
  matchLabels:
    target: "saver"
