# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "saver"

updateStrategy: "Recreate"

replicaCount: 1

service:
  port: 4537

volumes:
  - name: saver-tmp-dir
    emptyDir: {}
  - name: saver-data
    persistentVolumeClaim:
      claimName: saver-data

containers:
  - name: saver
    image: cyberdojo/saver
    tag: ""
    securityContext:
      runAsUser: 19663
      fsGroup: 65533
    volumeMounts:
      - name: saver-tmp-dir
        mountPath: /tmp
        readOnly: false
      - name: saver-data
        mountPath: /cyber-dojo
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 256Mi
    #livenessProbe:
    #  path: /alive?
    #  port: 4537
    #readinessProbe:
    #  path: /ready?
    #  port: 4537

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
